site_name: My Docs
theme:
  name: material
  language: en
extra_css:
  - stylesheets/lapis.css
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - tables
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - codehilite:    # 代码高亮，显示行号
      guess_lang: false
      linenums: true
      
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      linenums_style: table
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
